import { Component, Input } from '@angular/core';
import { ValidationErrors } from '@angular/forms';

@Component({
  selector:`app-form-error-list`,
  templateUrl:`./form-error-list.component.html`,
  styleUrls: ['./form-error-list.component.scss']
})
export class FormErrorListComponent {

  
  @Input() errorList: ValidationErrors | null | undefined;
  @Input() field: string | null | undefined = null;
  
  public errorTranslations: { [key: string]: string } = {
    'minlength':`Mínimo 8 caracteres.`,
    'noMatch':`Las contraseñas no coinciden.`,
    
    'pattern': `Inválido.`,    
    'accepted' :`Debe ser aceptado.`,
    'accepted_if' :`Debe ser aceptado cuando :other es :value.`,
    'active_url' :`No es una URL válida.`,
    'after' :`Debe ser una fecha después de :date.`,
    'after_or_equal' :`Debe ser una fecha después o igual a :date.`,
    'alpha' :`Sólo puede contener letras.`,
    'alpha_dash' :`Sólo puede contener letras, números y guiones.`,
    'alpha_num' :`Sólo puede contener letras y números.`,
    'array' :`Debe ser un arreglo.`,
    'ascii' :`Solo debe contener símbolos y caracteres alfanuméricos de un solo byte.`,
    'before' :`Debe ser una fecha antes de :date.`,
    'before_or_equal' :`Debe ser una fecha antes o igual a :date.`,
    
    'boolean' :`Debe ser verdadero o falso.`,
    'confirmed' :`El campo de confirmación no coincide.`,
    'current_password' :`La contraseña actual no es correcta`,
    'date' :`No es una fecha válida.`,
    'date_equals' :`Debe ser una fecha igual a :date.`,
    'date_format' :`No corresponde con el formato :format.`,
     'decimal' :`Debe tener :decimal decimales.`,
    'declined' :`Debe marcar como rechazado.`,
    'declined_if' :`Debe marcar como rechazado cuando :other es :value.`,
    'different' :`Deben ser diferentes.`,
    'digits' :`Debe ser de :digits dígitos.`,
    'digits_between' :`Debe tener entre :min y :max dígitos.`,
    'dimensions' :`N tiene una dimensión válida.`,
    'distinct' :`Tiene un valor duplicado.`,
    'doesnt_end_with' :`No puede finalizar con uno de los siguientes valores: :values.`,
    'doesnt_start_with' :`No puede comenzar con uno de los siguientes valores: :values.`,
    'email' :`El email no es válido.`,
    'ends_with' :`Debe terminar con alguno de los valores: :values.`,
    'enum' :`No es válido.`,
    'exists' :`No es válido.`,
    'file' :`Debe ser un archivo.`,
    'filled' :`Es requerido.`,
    
    'image' :`Debe ser una imagen.`,
    'in' :`No es válido.`,
    'in_array' :`No existe en :other.`,
    'integer' :`Debe ser un entero.`,
    'ip' :`Debe ser una dirección IP válida.`,
    'ipv4' :`Debe ser una dirección IPv4 válida.`,
    'ipv6' :`Debe ser una dirección IPv6 válida.`,
    'json' :`Debe ser una cadena JSON válida.`,
    'lowercase' :`Debe ser minusculas.`, 
        
    'mac_address' :`Debe ser una dirección MAC válida.`,
    'max_digits' :`No puede superar los :max dígitos.`,
    'mimes' :`Debe ser un archivo de tipo: :values.`,
    'mimetypes' :`Debe ser un archivo de tipo: :values.`,

    'min_digits' :`Debe ser como mínimo de :min dígitos.`,
    'missing' :`Debe faltar.`,
    'missing_if' :`Debe faltar cuando :other es :value`,
    'missing_unless' :`Debe faltar a menos que :other sea :value.`,
    'missing_with' :`Debe faltar cuando :values está presente.`,
    'missing_with_all' :`Debe faltar cuando :values están presentes`, 
    'multiple_of' :`Debe ser un múltiplo de :value.`,
    'not_in' :`La selección no es invalida.`,
    'not_regex' :`El formato no es válido.`,
    'numeric' :`Debe ser un número.`,
    'present' :`Debe estar presente.`,
    'prohibited' :`No está permitido.`,
    'prohibited_if' :`No está permitido cuando :other es :value.`,
    'prohibited_unless' :`No está permitido si :other no está en :values.`,
    'prohibits' :`No permite que :other esté presente.`,
    'regex' :`El formato no es válido.`,
    'required' :`Es requerido.`,
    'required_array_keys' :`Debe contener entradas para: :values.`,
    'required_if' :`Es requerido cuando el campo :other es :value.`,
    'required_unless' :`Es requerido a menos que :other esté presente en :values.`,
    'required_with' :`Es requerido cuando :values está presente.`,
    'required_with_all' :`Es requerido cuando :values está presente.`,
    'required_without' :`Es requerido cuando :values no está presente.`,
    'required_without_all' :`Es requerido cuando ningún :values está presente.`,
    'same' :`Debe coincidir.`,
    
    'starts_with' :`Debe empezar con uno de los siguientes valores :values`,
    'string' :`Debe ser una cadena.`,
    'timezone' :`Debe ser una zona válida.`,
    'unique' :`Ya ha sido tomado.`,
    'uploaded' :`No ha podido ser cargado.`,
    'uppercase' :`Debe estar en mayúsculas`, 
    'url' :`El formato no es válido.`,
    'ulid' :`Debe ser un ULID valido.`, 
    'uuid' :`Debe ser un UUID valido.`,
    
    'min.numeric' : `Debe tener al menos :min.`,
    'min.file' : `Debe tener al menos :min kilobytes.`,
    'min.string' : `Debe tener al menos :min caracteres.`,
    'min.array' : `Debe tener al menos :min elementos.`,
    
    'between.numeric' :`Debe estar entre :min - :max.`,
    'between.file' :`Debe estar entre :min - :max kilobytes.`,
    'between.string' :`Debe estar entre :min - :max caracteres.`,
    'between.array' :`Debe tener entre :min y :max elementos.`,

    'lt.numeric' : `Debe ser menor que :max.`,
    'lt.file' : `Debe ser menor que :max kilobytes.`,
    'lt.string' : `Debe ser menor que :max caracteres.`,
    'lt.array' : `Puede tener hasta :max elementos.`,
  
    'lte.numeric' : `Debe ser menor o igual que :max.`,
    'lte.file' : `Debe ser menor o igual que :max kilobytes.`,
    'lte.string' : `Debe ser menor o igual que :max caracteres.`,
    'lte.array' : `No puede tener más que :max elementos.`,
    
    'max.numeric' : `Debe ser menor que :max.`,
    'max.file' : `Debe ser menor que :max kilobytes.`,
    'max.string' : `Debe ser menor que :max caracteres.`,
    'max.array' : `Puede tener hasta :max elementos.`,

    'gt.numeric' : `Debe ser mayor que :value.`,
    'gt.file' : `Debe ser mayor que :value kilobytes.`,
    'gt.string' : `Debe ser mayor que :value caracteres.`,
    'gt.array' : `Puede tener hasta :value elementos.`,
    
    'gte.numeric' : `Debe ser mayor o igual que :value.`,
    'gte.file' : `Debe ser mayor o igual que :value kilobytes.`,
    'gte.string' : `Debe ser mayor o igual que :value caracteres.`,
    'gte.array' : `puede tener :value elementos o más.`,

    'size.numeric' :`Debe ser :size.`,
    'size.file' :`Debe tener :size kilobytes.`,
    'size.string' :`Debe tener :size caracteres.`,
    'size.array' :`Debe contener :size elementos.`,

    'password.mixed' :`Debe contener al menos una letra mayúscula y una minúscula.`,
    'password.letters' :`Debe contener al menos una letra.`,
    'password.symbols' :`Debe contener al menos un símbolo.`,
    'password.numbers' :`Debe contener al menos un número.`,
    'password.uncompromised' :`La contraseña ha aparecido en una fuga de datos. Elija una contraseña diferente.`,
  }
  public errorTranslationsWithNameField: { [key: string]: string } = {
    'pattern': `${this.field} inválido.`,    
    'accepted' :`El campo ${this.field} debe ser aceptado.`,
    'accepted_if' :`El campo ${this.field} debe ser aceptado cuando :other es :value.`,
    'active_url' :`El campo ${this.field} no es una URL válida.`,
    'after' :`El campo ${this.field} debe ser una fecha después de :date.`,
    'after_or_equal' :`El campo ${this.field} debe ser una fecha después o igual a :date.`,
    'alpha' :`El campo ${this.field} sólo puede contener letras.`,
    'alpha_dash' :`El campo ${this.field} sólo puede contener letras, números y guiones.`,
    'alpha_num' :`El campo ${this.field} sólo puede contener letras y números.`,
    'array' :`El campo ${this.field} debe ser un arreglo.`,
    'ascii' :`El ${this.field} solo debe contener símbolos y caracteres alfanuméricos de un solo byte.`,
    'before' :`El campo ${this.field} debe ser una fecha antes de :date.`,
    'before_or_equal' :`El campo ${this.field} debe ser una fecha antes o igual a :date.`,
    
    'boolean' :`El campo ${this.field} debe ser verdadero o falso.`,
    'confirmed' :`El campo de confirmación de ${this.field} no coincide.`,
    'current_password' :`La contraseña actual no es correcta`,
    'date' :`El campo ${this.field} no es una fecha válida.`,
    'date_equals' :`El campo ${this.field} debe ser una fecha igual a :date.`,
    'date_format' :`El campo ${this.field} no corresponde con el formato :format.`,
     'decimal' :`El ${this.field} debe tener :decimal decimales.`,
    'declined' :`El campo ${this.field} debe marcar como rechazado.`,
    'declined_if' :`El campo ${this.field} debe marcar como rechazado cuando :other es :value.`,
    'different' :`Los campos ${this.field} y :other deben ser diferentes.`,
    'digits' :`El campo ${this.field} debe ser de :digits dígitos.`,
    'digits_between' :`El campo ${this.field} debe tener entre :min y :max dígitos.`,
    'dimensions' :`El campo ${this.field} no tiene una dimensión válida.`,
    'distinct' :`El campo ${this.field} tiene un valor duplicado.`,
    'doesnt_end_with' :`El campo ${this.field} no puede finalizar con uno de los siguientes valores: :values.`,
    'doesnt_start_with' :`El campo ${this.field} no puede comenzar con uno de los siguientes valores: :values.`,
    'email' :`El formato del ${this.field} no es válido.`,
    'ends_with' :`El campo ${this.field} debe terminar con alguno de los valores: :values.`,
    'enum' :`El campo seleccionado en ${this.field} no es válido.`,
    'exists' :`El campo ${this.field} seleccionado no es válido.`,
    'file' :`El campo ${this.field} debe ser un archivo.`,
    'filled' :`El campo ${this.field} es requerido.`,
    
    'image' :`El campo ${this.field} debe ser una imagen.`,
    'in' :`El campo ${this.field} seleccionado no es válido.`,
    'in_array' :`El campo ${this.field} no existe en :other.`,
    'integer' :`El campo ${this.field} debe ser un entero.`,
    'ip' :`El campo ${this.field} debe ser una dirección IP válida.`,
    'ipv4' :`El campo ${this.field} debe ser una dirección IPv4 válida.`,
    'ipv6' :`El campo ${this.field} debe ser una dirección IPv6 válida.`,
    'json' :`El campo ${this.field} debe ser una cadena JSON válida.`,
    'lowercase' :`El ${this.field} debe ser minusculas.`, 
        
    'mac_address' :`El campo ${this.field} debe ser una dirección MAC válida.`,
    'max_digits' :`El campo ${this.field} no puede superar los :max dígitos.`,
    'mimes' :`El campo ${this.field} debe ser un archivo de tipo: :values.`,
    'mimetypes' :`El campo ${this.field} debe ser un archivo de tipo: :values.`,

    'min_digits' :`El campo ${this.field} debe ser como mínimo de :min dígitos.`,
    'missing' :`El campo ${this.field} debe faltar.`,
    'missing_if' :`El campo ${this.field} debe faltar cuando :other es :value`,
    'missing_unless' :`El campo ${this.field} debe faltar a menos que :other sea :value.`,
    'missing_with' :`El campo ${this.field} debe faltar cuando :values está presente.`,
    'missing_with_all' :`El campo ${this.field} debe faltar cuando :values están presentes`, 
    'multiple_of' :`El campo ${this.field} debe ser un múltiplo de :value.`,
    'not_in' :`El campo ${this.field} seleccionado es invalido.`,
    'not_regex' :`El formato del campo ${this.field} no es válido.`,
    'numeric' :`El campo ${this.field} debe ser un número.`,
    'present' :`El campo ${this.field} debe estar presente.`,
    'prohibited' :`El campo ${this.field} no está permitido.`,
    'prohibited_if' :`El campo ${this.field} no está permitido cuando :other es :value.`,
    'prohibited_unless' :`El campo ${this.field} no está permitido si :other no está en :values.`,
    'prohibits' :`El campo ${this.field} no permite que :other esté presente.`,
    'regex' :`El formato del campo ${this.field} no es válido.`,
    'required' :`El campo ${this.field} es requerido.`,
    'required_array_keys' :`El campo ${this.field} debe contener entradas para: :values.`,
    'required_if' :`El campo ${this.field} es requerido cuando el campo :other es :value.`,
    'required_unless' :`El campo ${this.field} es requerido a menos que :other esté presente en :values.`,
    'required_with' :`El campo ${this.field} es requerido cuando :values está presente.`,
    'required_with_all' :`El campo ${this.field} es requerido cuando :values está presente.`,
    'required_without' :`El campo ${this.field} es requerido cuando :values no está presente.`,
    'required_without_all' :`El campo ${this.field} es requerido cuando ningún :values está presente.`,
    'same' :`El campo ${this.field} y :other debe coincidir.`,
    
    'starts_with' :`El ${this.field} debe empezar con uno de los siguientes valores :values`,
    'string' :`El campo ${this.field} debe ser una cadena.`,
    'timezone' :`El campo ${this.field} debe ser una zona válida.`,
    'unique' :`El campo ${this.field} ya ha sido tomado.`,
    'uploaded' :`El campo ${this.field} no ha podido ser cargado.`,
    'uppercase' :`El ${this.field} debe estar en mayúsculas`, 
    'url' :`El formato de ${this.field} no es válido.`,
    'ulid' :`El ${this.field} debe ser un ULID valido.`, 
    'uuid' :`El ${this.field} debe ser un UUID valido.`,
    
    'min.numeric' : `El campo ${this.field} debe tener al menos :min.`,
    'min.file' : `El campo ${this.field} debe tener al menos :min kilobytes.`,
    'min.string' : `El campo ${this.field} debe tener al menos :min caracteres.`,
    'min.array' : `El campo ${this.field} debe tener al menos :min elementos.`,
    
    'between.numeric' :`El campo ${this.field} debe estar entre :min - :max.`,
    'between.file' :`El campo ${this.field} debe estar entre :min - :max kilobytes.`,
    'between.string' :`El campo ${this.field} debe estar entre :min - :max caracteres.`,
    'between.array' :`El campo ${this.field} debe tener entre :min y :max elementos.`,

    'lt.numeric' : `El campo ${this.field} debe ser menor que :max.`,
    'lt.file' : `El campo ${this.field} debe ser menor que :max kilobytes.`,
    'lt.string' : `El campo ${this.field} debe ser menor que :max caracteres.`,
    'lt.array' : `El campo ${this.field} puede tener hasta :max elementos.`,
  
    'lte.numeric' : `El campo ${this.field} debe ser menor o igual que :max.`,
    'lte.file' : `El campo ${this.field} debe ser menor o igual que :max kilobytes.`,
    'lte.string' : `El campo ${this.field} debe ser menor o igual que :max caracteres.`,
    'lte.array' : `El campo ${this.field} no puede tener más que :max elementos.`,
    
    'max.numeric' : `El campo ${this.field} debe ser menor que :max.`,
    'max.file' : `El campo ${this.field} debe ser menor que :max kilobytes.`,
    'max.string' : `El campo ${this.field} debe ser menor que :max caracteres.`,
    'max.array' : `El campo ${this.field} puede tener hasta :max elementos.`,

    'gt.numeric' : `El campo ${this.field} debe ser mayor que :value.`,
    'gt.file' : `El campo ${this.field} debe ser mayor que :value kilobytes.`,
    'gt.string' : `El campo ${this.field} debe ser mayor que :value caracteres.`,
    'gt.array' : `El campo ${this.field} puede tener hasta :value elementos.`,
    
    'gte.numeric' : `El campo ${this.field} debe ser mayor o igual que :value.`,
    'gte.file' : `El campo ${this.field} debe ser mayor o igual que :value kilobytes.`,
    'gte.string' : `El campo ${this.field} debe ser mayor o igual que :value caracteres.`,
    'gte.array' : `El campo ${this.field} puede tener :value elementos o más.`,

    'size.numeric' :`El campo ${this.field} debe ser :size.`,
    'size.file' :`El campo ${this.field} debe tener :size kilobytes.`,
    'size.string' :`El campo ${this.field} debe tener :size caracteres.`,
    'size.array' :`El campo ${this.field} debe contener :size elementos.`,

    'password.mixed' :`El ${this.field} debe contener al menos una letra mayúscula y una minúscula.`,
    'password.letters' :`El ${this.field} debe contener al menos una letra.`,
    'password.symbols' :`El ${this.field} debe contener al menos un símbolo.`,
    'password.numbers' :`El ${this.field} debe contener al menos un número.`,
    'password.uncompromised' :`El atributo ${this.field}  ha aparecido en una fuga de datos. Elija un ${this.field} diferente.`,
  }

  public getErrorTranslation(error: string): string {
    error = error.replace('validation.','');
    if(!this.errorTranslations[error]) return error;
    return this.errorTranslationsWithNameField[error] && this.field ? this.errorTranslationsWithNameField[error] : this.errorTranslations[error];
  }
}
